<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-11T10:54:49 IST" name="Default suite" finished-at="2021-10-11T10:55:19 IST" duration-ms="29940">
    <groups>
    </groups>
    <test started-at="2021-10-11T10:54:49 IST" name="Default test" finished-at="2021-10-11T10:55:19 IST" duration-ms="29940">
      <class name="PracticeTC.TC_30withAssert">
        <test-method is-config="true" signature="connectDB()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:54:49 IST" name="connectDB" finished-at="2021-10-11T10:54:49 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectDB -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:54:49 IST" name="launchBrowser" finished-at="2021-10-11T10:54:52 IST" duration-ms="3120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:54:52 IST" name="loginToApp" finished-at="2021-10-11T10:54:54 IST" duration-ms="2211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="tC_30()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:54:54 IST" name="tC_30" finished-at="2021-10-11T10:55:18 IST" duration-ms="23679" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [ Administrator - Organizations - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Organizations - vtiger CRM 5 - Commercial Open Source CRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [ Administrator - Organizations - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Organizations - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PracticeTC.TC_30withAssert.tC_30(TC_30withAssert.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC_30 -->
        <test-method is-config="true" signature="logoutofApp()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:55:18 IST" name="logoutofApp" finished-at="2021-10-11T10:55:19 IST" duration-ms="834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutofApp -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:55:19 IST" name="CloseBrowser" finished-at="2021-10-11T10:55:19 IST" duration-ms="65" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method is-config="true" signature="closeDB()[pri:0, instance:PracticeTC.TC_30withAssert@428640fa]" started-at="2021-10-11T10:55:19 IST" name="closeDB" finished-at="2021-10-11T10:55:19 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDB -->
      </class> <!-- PracticeTC.TC_30withAssert -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
